import { EarlyWarningService } from './early-warning.service';
export declare class EarlyWarningController {
    private readonly service;
    constructor(service: EarlyWarningService);
    create(body: any): Promise<{
        id: string;
        createdAt: Date;
        updatedAt: Date;
        deletedAt: Date | null;
        title: string;
        description: string;
        status: import("@prisma/client").$Enums.WarningStatus;
        severity: import("@prisma/client").$Enums.WarningSeverity;
        createdBy: string | null;
        incidentId: string | null;
        regionId: string | null;
        affectedAreas: string[];
        issuedAt: Date;
        expiresAt: Date;
        source: string | null;
    }>;
    list(query: any): Promise<{
        id: string;
        createdAt: Date;
        updatedAt: Date;
        deletedAt: Date | null;
        title: string;
        description: string;
        status: import("@prisma/client").$Enums.WarningStatus;
        severity: import("@prisma/client").$Enums.WarningSeverity;
        createdBy: string | null;
        incidentId: string | null;
        regionId: string | null;
        affectedAreas: string[];
        issuedAt: Date;
        expiresAt: Date;
        source: string | null;
    }[]>;
    getActive(query: any): Promise<{
        id: string;
        createdAt: Date;
        updatedAt: Date;
        deletedAt: Date | null;
        title: string;
        description: string;
        status: import("@prisma/client").$Enums.WarningStatus;
        severity: import("@prisma/client").$Enums.WarningSeverity;
        createdBy: string | null;
        incidentId: string | null;
        regionId: string | null;
        affectedAreas: string[];
        issuedAt: Date;
        expiresAt: Date;
        source: string | null;
    }[]>;
    getById(id: string): Promise<{
        id: string;
        createdAt: Date;
        updatedAt: Date;
        deletedAt: Date | null;
        title: string;
        description: string;
        status: import("@prisma/client").$Enums.WarningStatus;
        severity: import("@prisma/client").$Enums.WarningSeverity;
        createdBy: string | null;
        incidentId: string | null;
        regionId: string | null;
        affectedAreas: string[];
        issuedAt: Date;
        expiresAt: Date;
        source: string | null;
    }>;
    update(id: string, body: any): Promise<{
        id: string;
        createdAt: Date;
        updatedAt: Date;
        deletedAt: Date | null;
        title: string;
        description: string;
        status: import("@prisma/client").$Enums.WarningStatus;
        severity: import("@prisma/client").$Enums.WarningSeverity;
        createdBy: string | null;
        incidentId: string | null;
        regionId: string | null;
        affectedAreas: string[];
        issuedAt: Date;
        expiresAt: Date;
        source: string | null;
    }>;
    remove(id: string): Promise<{
        id: string;
        createdAt: Date;
        updatedAt: Date;
        deletedAt: Date | null;
        title: string;
        description: string;
        status: import("@prisma/client").$Enums.WarningStatus;
        severity: import("@prisma/client").$Enums.WarningSeverity;
        createdBy: string | null;
        incidentId: string | null;
        regionId: string | null;
        affectedAreas: string[];
        issuedAt: Date;
        expiresAt: Date;
        source: string | null;
    }>;
    expire(id: string): Promise<{
        id: string;
        createdAt: Date;
        updatedAt: Date;
        deletedAt: Date | null;
        title: string;
        description: string;
        status: import("@prisma/client").$Enums.WarningStatus;
        severity: import("@prisma/client").$Enums.WarningSeverity;
        createdBy: string | null;
        incidentId: string | null;
        regionId: string | null;
        affectedAreas: string[];
        issuedAt: Date;
        expiresAt: Date;
        source: string | null;
    }>;
}
//# sourceMappingURL=early-warning.controller.d.ts.map