import { PrismaService } from '../prisma/prisma.service';
export declare class DecisionService {
    private readonly prisma;
    constructor(prisma: PrismaService);
    create(data: any): Promise<{
        id: string;
        createdAt: Date;
        updatedAt: Date;
        deletedAt: Date | null;
        title: string;
        description: string;
        status: import("@prisma/client").$Enums.DecisionStatus;
        category: string;
        incidentId: string | null;
        impact: import("@prisma/client").$Enums.DecisionImpact;
        urgency: import("@prisma/client").$Enums.DecisionUrgency;
        reasoning: string | null;
        alternatives: import("@prisma/client/runtime/library").JsonValue | null;
        inputFactors: import("@prisma/client/runtime/library").JsonValue | null;
        riskLevel: import("@prisma/client").$Enums.DecisionImpact | null;
        selectedOption: string | null;
        rationale: string | null;
        requestedBy: string;
        decidedBy: string | null;
        decidedAt: Date | null;
    }>;
    list(filter: any): Promise<{
        id: string;
        createdAt: Date;
        updatedAt: Date;
        deletedAt: Date | null;
        title: string;
        description: string;
        status: import("@prisma/client").$Enums.DecisionStatus;
        category: string;
        incidentId: string | null;
        impact: import("@prisma/client").$Enums.DecisionImpact;
        urgency: import("@prisma/client").$Enums.DecisionUrgency;
        reasoning: string | null;
        alternatives: import("@prisma/client/runtime/library").JsonValue | null;
        inputFactors: import("@prisma/client/runtime/library").JsonValue | null;
        riskLevel: import("@prisma/client").$Enums.DecisionImpact | null;
        selectedOption: string | null;
        rationale: string | null;
        requestedBy: string;
        decidedBy: string | null;
        decidedAt: Date | null;
    }[]>;
    getById(id: string): Promise<{
        id: string;
        createdAt: Date;
        updatedAt: Date;
        deletedAt: Date | null;
        title: string;
        description: string;
        status: import("@prisma/client").$Enums.DecisionStatus;
        category: string;
        incidentId: string | null;
        impact: import("@prisma/client").$Enums.DecisionImpact;
        urgency: import("@prisma/client").$Enums.DecisionUrgency;
        reasoning: string | null;
        alternatives: import("@prisma/client/runtime/library").JsonValue | null;
        inputFactors: import("@prisma/client/runtime/library").JsonValue | null;
        riskLevel: import("@prisma/client").$Enums.DecisionImpact | null;
        selectedOption: string | null;
        rationale: string | null;
        requestedBy: string;
        decidedBy: string | null;
        decidedAt: Date | null;
    }>;
    update(id: string, data: any): Promise<{
        id: string;
        createdAt: Date;
        updatedAt: Date;
        deletedAt: Date | null;
        title: string;
        description: string;
        status: import("@prisma/client").$Enums.DecisionStatus;
        category: string;
        incidentId: string | null;
        impact: import("@prisma/client").$Enums.DecisionImpact;
        urgency: import("@prisma/client").$Enums.DecisionUrgency;
        reasoning: string | null;
        alternatives: import("@prisma/client/runtime/library").JsonValue | null;
        inputFactors: import("@prisma/client/runtime/library").JsonValue | null;
        riskLevel: import("@prisma/client").$Enums.DecisionImpact | null;
        selectedOption: string | null;
        rationale: string | null;
        requestedBy: string;
        decidedBy: string | null;
        decidedAt: Date | null;
    }>;
    approve(id: string, selectedOption: string, rationale: string): Promise<{
        id: string;
        createdAt: Date;
        updatedAt: Date;
        deletedAt: Date | null;
        title: string;
        description: string;
        status: import("@prisma/client").$Enums.DecisionStatus;
        category: string;
        incidentId: string | null;
        impact: import("@prisma/client").$Enums.DecisionImpact;
        urgency: import("@prisma/client").$Enums.DecisionUrgency;
        reasoning: string | null;
        alternatives: import("@prisma/client/runtime/library").JsonValue | null;
        inputFactors: import("@prisma/client/runtime/library").JsonValue | null;
        riskLevel: import("@prisma/client").$Enums.DecisionImpact | null;
        selectedOption: string | null;
        rationale: string | null;
        requestedBy: string;
        decidedBy: string | null;
        decidedAt: Date | null;
    }>;
    getStats(): Promise<{
        total: number;
        pending: number;
        approved: number;
        rejected: number;
        deferred: number;
        avgDecisionTime: number;
        byCategory: {};
    }>;
}
//# sourceMappingURL=decision.service.d.ts.map