import { DecisionService } from './decision.service';
export declare class DecisionController {
    private readonly service;
    constructor(service: DecisionService);
    execute(body: any): Promise<{
        id: string;
        createdAt: Date;
        updatedAt: Date;
        deletedAt: Date | null;
        title: string;
        description: string;
        status: import("@prisma/client").$Enums.DecisionStatus;
        category: string;
        incidentId: string | null;
        impact: import("@prisma/client").$Enums.DecisionImpact;
        urgency: import("@prisma/client").$Enums.DecisionUrgency;
        reasoning: string | null;
        alternatives: import("@prisma/client/runtime/library").JsonValue | null;
        inputFactors: import("@prisma/client/runtime/library").JsonValue | null;
        riskLevel: import("@prisma/client").$Enums.DecisionImpact | null;
        selectedOption: string | null;
        rationale: string | null;
        requestedBy: string;
        decidedBy: string | null;
        decidedAt: Date | null;
    }>;
    list(query: any): Promise<{
        id: string;
        createdAt: Date;
        updatedAt: Date;
        deletedAt: Date | null;
        title: string;
        description: string;
        status: import("@prisma/client").$Enums.DecisionStatus;
        category: string;
        incidentId: string | null;
        impact: import("@prisma/client").$Enums.DecisionImpact;
        urgency: import("@prisma/client").$Enums.DecisionUrgency;
        reasoning: string | null;
        alternatives: import("@prisma/client/runtime/library").JsonValue | null;
        inputFactors: import("@prisma/client/runtime/library").JsonValue | null;
        riskLevel: import("@prisma/client").$Enums.DecisionImpact | null;
        selectedOption: string | null;
        rationale: string | null;
        requestedBy: string;
        decidedBy: string | null;
        decidedAt: Date | null;
    }[]>;
    getStats(): Promise<{
        total: number;
        pending: number;
        approved: number;
        rejected: number;
        deferred: number;
        avgDecisionTime: number;
        byCategory: {};
    }>;
    getStatus(id: string): Promise<{
        id: string;
        createdAt: Date;
        updatedAt: Date;
        deletedAt: Date | null;
        title: string;
        description: string;
        status: import("@prisma/client").$Enums.DecisionStatus;
        category: string;
        incidentId: string | null;
        impact: import("@prisma/client").$Enums.DecisionImpact;
        urgency: import("@prisma/client").$Enums.DecisionUrgency;
        reasoning: string | null;
        alternatives: import("@prisma/client/runtime/library").JsonValue | null;
        inputFactors: import("@prisma/client/runtime/library").JsonValue | null;
        riskLevel: import("@prisma/client").$Enums.DecisionImpact | null;
        selectedOption: string | null;
        rationale: string | null;
        requestedBy: string;
        decidedBy: string | null;
        decidedAt: Date | null;
    }>;
    approve(id: string, body: any): Promise<{
        id: string;
        createdAt: Date;
        updatedAt: Date;
        deletedAt: Date | null;
        title: string;
        description: string;
        status: import("@prisma/client").$Enums.DecisionStatus;
        category: string;
        incidentId: string | null;
        impact: import("@prisma/client").$Enums.DecisionImpact;
        urgency: import("@prisma/client").$Enums.DecisionUrgency;
        reasoning: string | null;
        alternatives: import("@prisma/client/runtime/library").JsonValue | null;
        inputFactors: import("@prisma/client/runtime/library").JsonValue | null;
        riskLevel: import("@prisma/client").$Enums.DecisionImpact | null;
        selectedOption: string | null;
        rationale: string | null;
        requestedBy: string;
        decidedBy: string | null;
        decidedAt: Date | null;
    }>;
    reject(id: string, body: any): Promise<{
        id: string;
        createdAt: Date;
        updatedAt: Date;
        deletedAt: Date | null;
        title: string;
        description: string;
        status: import("@prisma/client").$Enums.DecisionStatus;
        category: string;
        incidentId: string | null;
        impact: import("@prisma/client").$Enums.DecisionImpact;
        urgency: import("@prisma/client").$Enums.DecisionUrgency;
        reasoning: string | null;
        alternatives: import("@prisma/client/runtime/library").JsonValue | null;
        inputFactors: import("@prisma/client/runtime/library").JsonValue | null;
        riskLevel: import("@prisma/client").$Enums.DecisionImpact | null;
        selectedOption: string | null;
        rationale: string | null;
        requestedBy: string;
        decidedBy: string | null;
        decidedAt: Date | null;
    }>;
    defer(id: string, body: any): Promise<{
        id: string;
        createdAt: Date;
        updatedAt: Date;
        deletedAt: Date | null;
        title: string;
        description: string;
        status: import("@prisma/client").$Enums.DecisionStatus;
        category: string;
        incidentId: string | null;
        impact: import("@prisma/client").$Enums.DecisionImpact;
        urgency: import("@prisma/client").$Enums.DecisionUrgency;
        reasoning: string | null;
        alternatives: import("@prisma/client/runtime/library").JsonValue | null;
        inputFactors: import("@prisma/client/runtime/library").JsonValue | null;
        riskLevel: import("@prisma/client").$Enums.DecisionImpact | null;
        selectedOption: string | null;
        rationale: string | null;
        requestedBy: string;
        decidedBy: string | null;
        decidedAt: Date | null;
    }>;
}
//# sourceMappingURL=decision.controller.d.ts.map